version: "3"
services:
  postgres:
    container_name: PollkemonDB
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pollkemon
      - POSTGRES_PASSWORD=pollkemon
      - POSTGRES_DB=pollkemon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pollkemon"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: PollkemonBackend
    build: ./backend/
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pollkemon
      - DB_USER=pollkemon
      - DB_PASS=pollkemon
      - PORT=8080
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local
